- id: '1743336042165'
  alias: MotionActivatedLights
  description: ''
  triggers:
  - type: occupied
    device_id: 5541e0e7fe44afe1a922c616b3af43b0
    entity_id: 788c9d2ee36efd5f3c391e864410d15c
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      label_id: outdoorlights
  mode: single
- id: '1743339482521'
  alias: Tænd udendørslys når der er mørkt
  description: ''
  triggers:
  - type: illuminance
    device_id: 5541e0e7fe44afe1a922c616b3af43b0
    entity_id: e673213710bda8a9d629643ed50728fc
    domain: sensor
    trigger: device
    below: 10
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 30
    target:
      label_id: outdoorlights
  - action: scene.create
    metadata: {}
    data:
      scene_id: carport_nuvaerende_lys
      snapshot_entities:
      - update.carport_lys
      - update.hoveddor_lys
    enabled: true
  mode: single
- id: '1743342440307'
  alias: Tænd carport lys ved bevægelse
  description: ''
  triggers:
  - type: motion
    device_id: 5541e0e7fe44afe1a922c616b3af43b0
    entity_id: 788c9d2ee36efd5f3c391e864410d15c
    domain: binary_sensor
    trigger: device
    id: Bevægelse
  - type: no_motion
    device_id: 5541e0e7fe44afe1a922c616b3af43b0
    entity_id: 788c9d2ee36efd5f3c391e864410d15c
    domain: binary_sensor
    trigger: device
    id: Ingen bevægelse
  - type: illuminance
    device_id: 5541e0e7fe44afe1a922c616b3af43b0
    entity_id: e673213710bda8a9d629643ed50728fc
    domain: sensor
    trigger: device
    above: 20
    id: Lyst udenfor
  - type: illuminance
    device_id: 5541e0e7fe44afe1a922c616b3af43b0
    entity_id: e673213710bda8a9d629643ed50728fc
    domain: sensor
    trigger: device
    below: 10
    id: Mørkt udenfor
  conditions:
  - condition: time
    after: '17:00:00'
    before: 00:00:00
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.udendors_lys_tilstand
        state: 'Off'
      - condition: trigger
        id:
        - Mørkt udenfor
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 30
        target:
          entity_id: light.grp_udendors_lys
      - action: input_select.select_option
        metadata: {}
        data:
          option: Dim
        target:
          entity_id: input_select.udendors_lys_tilstand
    - conditions:
      - condition: state
        entity_id: input_select.udendors_lys_tilstand
        state: Dim
      sequence:
      - if:
        - condition: trigger
          id:
          - Bevægelse
        then:
        - action: light.turn_on
          metadata: {}
          data:
            brightness_pct: 100
          target:
            entity_id: light.grp_udendors_lys
        - action: input_select.select_option
          metadata: {}
          data:
            option: Full
      - if:
        - condition: trigger
          id:
          - Lyst udenfor
        then:
        - action: light.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: light.grp_udendors_lys
        - action: input_select.select_option
          metadata: {}
          data:
            option: 'Off'
    - conditions:
      - condition: state
        entity_id: input_select.udendors_lys_tilstand
        state: Full
      - condition: trigger
        id:
        - Ingen bevægelse
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 30
        target:
          entity_id: light.grp_udendors_lys
      - action: input_select.select_option
        metadata: {}
        data:
          option: Dim
        target:
          entity_id: input_select.udendors_lys_tilstand
  mode: single
- id: '1743343061100'
  alias: Gendan lys i carport ved mangelende bevægelse
  description: ''
  triggers:
  - type: not_occupied
    device_id: 5541e0e7fe44afe1a922c616b3af43b0
    entity_id: 788c9d2ee36efd5f3c391e864410d15c
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 3
      seconds: 0
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.carport_nuvaerende_lys
  mode: single
- id: '1743343694707'
  alias: Sluk carport lys når der er lyst
  description: ''
  triggers:
  - type: illuminance
    device_id: 5541e0e7fe44afe1a922c616b3af43b0
    entity_id: e673213710bda8a9d629643ed50728fc
    domain: sensor
    trigger: device
    above: 15
    for:
      hours: 0
      minutes: 10
      seconds: 0
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      label_id: outdoorlights
  - action: scene.create
    metadata: {}
    data:
      scene_id: carport_nuvaerende_lys
      snapshot_entities:
      - update.carport_lys
      - light.hoveddor_lys
    enabled: true
  mode: single
- id: '1743347783862'
  alias: Tænd carport og hoveddør lys sammen
  description: ''
  triggers:
  - type: changed_states
    device_id: a71513d60e77096c7de8f9fcecceec6d
    entity_id: 2a2836467e2b5c1ff31f5532c3e0af80
    domain: light
    trigger: device
  - type: changed_states
    device_id: aa87d6bc67b7fe1b4b26a3a13ccc31fb
    entity_id: 523dfba4f27f7de6f0c5bceaae676d18
    domain: light
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      device_id:
      - a71513d60e77096c7de8f9fcecceec6d
      - aa87d6bc67b7fe1b4b26a3a13ccc31fb
  mode: single
- id: '1743628225706'
  alias: 'Sluk lys til midnat '
  description: ''
  triggers:
  - trigger: time
    at: 00:00:00
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      label_id: outdoorlights
  - action: scene.create
    metadata: {}
    data:
      scene_id: carport_nuvaerende_lys
      snapshot_entities:
      - update.carport_lys
      - update.hoveddor_lys
    enabled: true
  mode: single
