
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
- platform: google_translate

# IKEA Trådfri
tradfri:
  host: "192.168.1.20"

logger:
  default: error
  logs:
      my_error: error

# Cicardian lighting, see doc at:
# https://community.home-assistant.io/t/circadian-lighting-custom-component/61246
circadian_lighting:
  min_colortemp: 1000
  max_colortemp: 7000
  sunrise_offset: "00:00:00"

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named  script/
scene: !include scenes.yaml
sensor: !include sensors.yaml
light: !include light.yaml
switch: !include fluxLight.yaml

# See https://www.home-assistant.io/integrations/asuswrt/
asuswrt:
  host: "192.168.1.1"
  username: admin
  password: !secret asusWRTPassword
  sensors:
    - devices           # sensor.asuswrt_devices_connected
    - upload            # sensor.asuswrt_download (unit_of_measurement: Gigabyte - Daily accumulation)
    - download          # sensor.asuswrt_download_speed (unit_of_measurement: Mbit/s)
    - upload_speed      # sensor.asuswrt_upload (unit_of_measurement: Gigabyte - Daily accumulation)
    - download_speed    # sensor.asuswrt_upload_speed (unit_of_measurement: Mbit/s)

lovelace:
  mode: yaml


# pi_hole:
# - host: "192.168.1.20"


# Wake up light stuff
# see: https://www.wouterbulten.nl/blog/tech/custom-wake-up-light-with-home-assistant/
input_boolean:
  wakeup_enabled:
    name: "Wake-up lights"
    #initial: on
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "Enable Wake-up on weekends"
    #initial: off # I disable the system on default on weekends
    icon: mdi:calendar-blank
  wakeup_test:
    name: "Test Wake-up"
    #initial: off # I disable the system on default on weekends
    icon: mdi:calendar-blank

input_datetime:
  wakeup_time:
    name: "Start lights at"
    has_time: true
    has_date: false

homeassistant:
  packages:
    lightpack:
      counter:
        # https://www.home-assistant.io/integrations/counter/
        stuecounter:
          initial: 0
          step: 1

      input_boolean:
        disableincrement:
          initial: "off"

      automation:
        - id: hass_startup
          alias: 'Hass startup'
          trigger:
          - platform: homeassistant
            event: start
          action:
          - service: switch.turn_on
            entity_id: switch.circadian_lighting_cicardian_lights
          - service: counter.reset
            entity_id: counter.stuecounter

        - alias: 'resetLightToggleCounter'
          initial_state: "on"
          trigger:
          - platform: time_pattern
            seconds: /10
          action:
          - service: counter.reset
            entity_id: counter.stuecounter

        - alias: "incrementStueCounter"
          initial_state: "on"
          trigger:
          - platform: state
            entity_id: light.stue_spot
            from: "off"
            to: "on"
          condition:
          - condition: state
            entity_id: input_boolean.disableincrement
            state: "off"
          action:
          - service: counter.increment
            entity_id: counter.stuecounter

        - alias: "toggleManualOverride"
          initial_state: "on"
          trigger:
          - platform: numeric_state
            entity_id: counter.stuecounter
            above: 2
            # below: 5
          action:
          - service: input_boolean.turn_on
            entity_id: input_boolean.disableincrement
          - service: switch.toggle
            entity_id: switch.circadian_lighting_cicardian_lights
          - service: light.turn_on
            entity_id: light.hele_stue_lys
          - service: counter.reset
            entity_id: counter.stuecounter
          - service: input_boolean.turn_off
            entity_id: input_boolean.disableincrement

          - condition: state
            entity_id: switch.circadian_lighting_cicardian_lights
            state: "off"
          - service: input_boolean.turn_on
            entity_id: input_boolean.disableincrement
          - service: light.turn_on
            data:
              entity_id: light.hele_stue_lys
              transition: 2
              # color_temp: 6000
              brightness_pct: 100
          - service: counter.reset
            entity_id: counter.stuecounter
          - service: input_boolean.turn_off
            entity_id: input_boolean.disableincrement


