
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
- platform: google_translate

# IKEA Trådfri
tradfri:
  host: "192.168.1.20"

logger:
  default: error
  logs:
      my_error: error

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named  script/
scene: !include scenes.yaml
sensor: !include sensors.yaml
light: !include light.yaml

lovelace:
  mode: yaml


# pi_hole:
# - host: "192.168.1.20"

homeassistant:
  packages:
    wakeuplights: !include_dir_merge_named packages/wakeUpLights
    circadianlights: !include_dir_merge_named packages/circadianLighting
    medialights: !include_dir_merge_named packages/mediaLights
    awayfromhome: !include_dir_merge_named packages/awayFromHome


