
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
- platform: google_translate

# IKEA Trådfri
tradfri:
  host: "192.168.1.20"

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named  script/
scene: !include scenes.yaml
sensor: !include sensors.yaml
light: !include light.yaml
switch: !include fluxLight.yaml



lovelace:
  mode: yaml

# pi_hole:
# - host: "192.168.1.20"


# Wake up light stuff
# see: https://www.wouterbulten.nl/blog/tech/custom-wake-up-light-with-home-assistant/
input_boolean:
  wakeup_enabled:
    name: "Wake-up lights"
    #initial: on
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "Enable Wake-up on weekends"
    #initial: off # I disable the system on default on weekends
    icon: mdi:calendar-blank
  wakeup_test:
    name: "Test Wake-up"
    #initial: off # I disable the system on default on weekends
    icon: mdi:calendar-blank

input_datetime:
  wakeup_time:
    name: "Start lights at"
    has_time: true
    has_date: false