
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
- platform: google_translate

# IKEA Trådfri
tradfri:
  host: "192.168.1.20"

logger:
  default: error
  logs:
      my_error: error

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named  script/
scene: !include scenes.yaml
sensor: !include sensors.yaml
light: !include light.yaml

# See https://www.home-assistant.io/integrations/asuswrt/
# Password authentication / telnet is no longer supported, so must use SSH auth instead:
# https://community.home-assistant.io/t/asuswrt-asus-merlin-not-working-after-firmware-update/62027
# https://community.home-assistant.io/t/how-i-got-asuswrt-device-tracker-working-with-ssh-key-files/47787/32
asuswrt:
  host: "192.168.1.1"
  username: admin
  ssh_key: secrets/ssh/id_rsa_ansibleAdminHome
  # password: !secret asusWRTPassword
  sensors:
    - devices           # sensor.asuswrt_devices_connected
    - upload            # sensor.asuswrt_download (unit_of_measurement: Gigabyte - Daily accumulation)
    - download          # sensor.asuswrt_download_speed (unit_of_measurement: Mbit/s)
    - upload_speed      # sensor.asuswrt_upload (unit_of_measurement: Gigabyte - Daily accumulation)
    - download_speed    # sensor.asuswrt_upload_speed (unit_of_measurement: Mbit/s)

lovelace:
  mode: yaml


# pi_hole:
# - host: "192.168.1.20"


homeassistant:
  packages:
    wakeuplights: !include_dir_merge_named packages/wakeUpLights
    circadianlights: !include_dir_merge_named packages/circadianLighting
    medialights: !include_dir_merge_named packages/mediaLights


