- platform: group
  name: Badeværelse lys
  entities:
    - light.badevaerelse
    - light.badevaerelse_2
    - light.badevaerelse_3

- platform: group
  name: Stue lys
  entities:
    - light.stue_spot
    - light.stue_spot_2
    - light.stue_spot_3
    - light.stue_spot_4

- platform: group
  name: Spisestue lys
  entities:
    - light.spisestue_spot
    - light.spisestue_spot_2
    - light.spisestue_spot_3
    - light.spisestue_spot_4
    - light.spisebord

- platform: group
  name: Hele Stue lys
  entities:
    - light.stue_spot
    - light.stue_spot_2
    - light.stue_spot_3
    - light.stue_spot_4
    - light.spisestue_spot
    - light.spisestue_spot_2
    - light.spisestue_spot_3
    - light.spisestue_spot_4
    - light.spisebord

- platform: group
  name: Køkken lys
  entities:
    - light.kokken
    - light.kokken_3
    - light.kokken_2

- platform: group
  name: Soveværelse lys
  entities:
    - light.sovevaerelse
    - light.sovevaerelse_2
    - light.sovevaerelse_3

- platform: group
  name: Gang lys
  entities:
    - light.gang
    - light.gang_2

# sensor.tradfri_remote_control_3
# sensor.tradfri_motion_sensor
# sensor.tradfri_remote_control_7
# sensor.tradfri_remote_control_6
# sensor.ved_dor
# sensor.ved_dor_2
# sensor.ved_seng
# sensor.tradfri_remote_control_2
