# - platform: group
#   name: grp Kontor
#   entities:
#     - light.kontor_1
#     - light.kontor_2
#     - light.kontor_3

# - platform: group
#   name: grp Soveværelse
#   entities:
#     - light.sovevaerelse
#     - light.sovevaerelse_2
#     - light.sovevaerelse_3
#     - light.sovevaerelse_spot_1
#     - light.sovevaerelse_spot_2
#     - light.sovevaerelse_spot_3
#     - light.sovevaerelse_spot_4

# - platform: group
#   name: grp Stue
#   entities:
#     - light.sofabord

# - platform: group
#   name: grp Entre
#   entities:
#     - light.repos_nede_1
#     - light.repos_nede_2
#     - light.repos_nede_3
#     - light.repos_nede_4
#     - light.repos_1
#     - light.repos_2
#     - light.repos_3

- platform: group
  name: grp Udendørs lys
  entities: 
    - light.carport_lys
    - light.hoveddor_lys

# - platform: group
#   name: grp Carport
#   entities:
#     - light.carport_lys

# - platform: group
#   name: grp Hoveddør
#   entities:
#     - light.hoveddor_lys
