title: Jyllandsgade11
views:
  - path: default_view
    title: Home
    badges:
      # - entity: binary_sensor.updater
      # - entity: person.tom_erik
      # - entity: sensor.time
      # - entity: sensor.local_ip
      # - entity: sensor.tradfri_remote_control_7
      # - entity: sensor.tradfri_remote_control_2
      # - entity: sensor.ved_dor
      # - entity: sensor.ved_dor_2
      # - entity: sensor.tradfri_remote_control_6
      # - entity: sensor.tradfri_remote_control_3
      # - entity: sensor.transmission_down_speed
      # - entity: sensor.transmission_up_speed
      # - entity: sensor.transmission_status
      # - entity: sensor.transmission_active_torrents
      # - entity: sensor.transmission_paused_torrents
      # - entity: sensor.transmission_total_torrents
      # - entity: sensor.transmission_completed_torrents
      # - entity: sensor.transmission_started_torrents
      # - entity: sun.sun

    cards:

      # - type: entities
      #   entities:
      #     - light.badevaerelse
      #     - light.badevaerelse_2
      #     - light.badevaerelse_3
      #   title: Bathroom

      # - type: entities
      #   entities:
      #     - light.sovevaerelse
      #     - light.sovevaerelse_2
      #     - light.sovevaerelse_3
      #   title: Bedroom

      # - type: entities
      #   entities:
      #     - light.spisestue_spot
      #     - light.spisebord
      #     - light.spisestue_spot_2
      #     - light.spisestue_spot_3
      #     - light.spisestue_spot_4
      #   title: Dining room

      # - type: entities
      #   entities:
      #     - light.gang
      #     - light.gang_2
      #   title: Hallway

      # - type: entities
      #   entities:
      #     - light.kokken
      #     - light.kokken_2
      #     - light.kokken_3
      #   title: Kitchen

      # - type: entities
      #   entities:
      #     # - sensor.hp_officejet_pro_x451dw_printer
      #     # - light.stue_spot
      #     # - light.stue_spot_2
      #     # - light.stue_spot_3
      #     # - light.stue_spot_4
      #     # - sensor.skrivebord
      #     # - switch.media_corner_control_outlet
      #     # - switch.desk_control_outlet
      #     # - media_player.chromecastaudio4176
      #     # - media_player.projector
      #   title: Living Room

      - type: media-control
        entity: media_player.projector

      - type: media-control
        entity: media_player.plex_plex_cast_chromecast_3

      - type: media-control
        entity: media_player.chromecastaudio4176

      - type: media-control
        entity: media_player.plex_plex_cast_chromecast

      - type: entities
        entities:
          - light.grp_hele_stue
          - light.grp_spisestue
          - light.grp_stue
          - light.grp_badevaerelse
          - light.grp_gang
          - light.grp_kokken
          - light.grp_sovevaerelse
        title: Light

      - type: weather-forecast
        entity: weather.jyllandsgade11

      - type: entities
        entities:
          - switch.circadian_lighting_stue
          - switch.circadian_lighting_spisestue
          - switch.circadian_lighting_kokken
          - switch.circadian_lighting_sovevaerelse
          - switch.circadian_lighting_badevaerelse
          - switch.circadian_lighting_gang
        title: Automations

      # - type: entities
      #   entities:
      #     - counter.stue
      #     - counter.spisestue
      #     - counter.kokken
      #     - counter.sovevaerelse
      #     - counter.badevaerelse
      #     - counter.gang

      - type: entities
        entities:
          - input_boolean.enablewakeuplights
          - sensor.nextalarm
        title: Wake-up Lights
