title: Jyllandsgade11
views:
  - path: default_view
    title: Home
    # badges:
    #   - entity: person.tom_erik

    cards:
      - type: media-control
        entity: media_player.projector

      - type: media-control
        entity: media_player.plex_plex_cast_chromecast_3

      - type: media-control
        entity: media_player.chromecastaudio4176

      - type: media-control
        entity: media_player.plex_plex_cast_chromecast

      - type: entities
        entities:
          # - entity: light.grp_hele_stue
          #   type: custom:multiple-entity-row
          #   name: Hele Stue
          #   state_header: Hele stue
          #   toggle: true
          #   state_color: true
          #   entities:
          #     - entity: light.grp_stue
          #       name: Stue
          #       toggle: true
          #     - entity: light.grp_spisestue
          #       name: Spisestue
          #       toggle: true

          # - type: divider
          - entity: light.grp_stue
            type: custom:multiple-entity-row
            name: Stue
            state_header: Lys
            toggle: true
            state_color: true
            entities:
              - entity: switch.circadian_lighting_stue
                name: Circadian
                toggle: true

          - type: custom:slider-entity-row
            entity: light.grp_stue
            name: Brightness
            hide_state: true
            icon: mdi:brightness-percent
          - type: custom:slider-entity-row
            entity: light.grp_stue
            name: Color temperature
            attribute: color_temp
            hide_state: true
            icon: mdi:temperature-kelvin

          - type: divider
          - entity: light.grp_spisestue
            type: custom:multiple-entity-row
            name: Spisestue
            state_header: Lys
            toggle: true
            state_color: true
            entities:
              - entity: switch.circadian_lighting_spisestue
                name: Circadian
                toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_spisestue
            name: Brightness
            hide_state: true
            icon: mdi:brightness-percent
          - type: custom:slider-entity-row
            entity: light.grp_spisestue
            name: Color temperature
            attribute: color_temp
            hide_state: true
            icon: mdi:temperature-kelvin

          - type: divider
          - entity: light.grp_sovevaerelse
            type: custom:multiple-entity-row
            name: Soveværelse
            state_header: Lys
            toggle: true
            state_color: true
            entities:
              - entity: switch.circadian_lighting_sovevaerelse
                name: Circadian
                toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_sovevaerelse
            name: Brightness
            hide_state: true
            icon: mdi:brightness-percent
          - type: custom:slider-entity-row
            entity: light.grp_sovevaerelse
            name: Color temperature
            attribute: color_temp
            hide_state: true
            icon: mdi:temperature-kelvin

          - type: divider
          - entity: light.grp_kokken
            type: custom:multiple-entity-row
            name: Køkken
            state_header: Lys
            toggle: true
            state_color: true
            entities:
              - entity: switch.circadian_lighting_kokken
                name: Circadian
                toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_kokken
            name: Brightness
            hide_state: true
            icon: mdi:brightness-percent
          - type: custom:slider-entity-row
            entity: light.grp_kokken
            name: Color temperature
            attribute: color_temp
            hide_state: true
            icon: mdi:temperature-kelvin


          - type: divider
          - entity: light.grp_badevaerelse
            type: custom:multiple-entity-row
            name: Badeværelse
            state_header: Lys
            toggle: true
            state_color: true
            entities:
              - entity: switch.circadian_lighting_badevaerelse
                name: Circadian
                toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_badevaerelse
            name: Brightness
            hide_state: true
            icon: mdi:brightness-percent
          - type: custom:slider-entity-row
            entity: light.grp_badevaerelse
            name: Color temperature
            attribute: color_temp
            hide_state: true
            icon: mdi:temperature-kelvin


          - type: divider
          - entity: light.grp_gang
            type: custom:multiple-entity-row
            name: Gang
            state_header: Lys
            toggle: true
            state_color: true
            entities:
              - entity: switch.circadian_lighting_gang
                name: Circadian
                toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_gang
            name: Brightness
            hide_state: true
            icon: mdi:brightness-percent
          - type: custom:slider-entity-row
            entity: light.grp_gang
            name: Color temperature
            attribute: color_temp
            hide_state: true
            icon: mdi:temperature-kelvin

        title: Lights
        show_header_toggle: false

      - type: weather-forecast
        entity: weather.jyllandsgade11

      - type: entities
        entities:
          - input_boolean.enablewakeuplights
          - sensor.nextalarm
        title: Wake-up Lights

