views:
  - path: default_view
    title: Home


    cards:
      # - type: media-control
      #   entity: media_player.plex_plex_cast_chromecast_3

      # - type: media-control
      #   entity: media_player.chromecastaudio4176

      # - type: media-control
      #   entity: media_player.plex_plex_cast_chromecast

      - type: entities
        entities:
          - entity: input_number.udendors_dim_brightness
            name: Dim brightness level
          - entity: input_number.udendors_full_brightness
            name: Full brightness level
          - entity: input_number.udendors_min_lux_for_dim
            name: Min. lux for dim activation
          - entity: input_select.udendors_lys_tilstand
            name: Tilstand
          - entity: input_boolean.dim_available
            name: Dæmpet tilgængelig
          - entity: input_datetime.tid_for_dim_available1
          - entity: input_datetime.tid_for_dim_unavailable1
          - entity: input_datetime.tid_for_dim_available2
          - entity: input_datetime.tid_for_dim_unavailable2
        title: Udendørs lys tilstand

      - type: entities
        entities:
          - entity: light.hoveddor_lys
            name: Hoveddør

          - entity: light.carport_lys
            name: Carport

          - entity: light.kontor_lys
            name: Kontor

          - entity: light.grp_udendors_lys
            name: Outdoor lights group

          # - entity: light.grp_hele_stue
          #   type: custom:multiple-entity-row
          #   name: Hele Stue
          #   state_header: Hele stue
          #   toggle: true
          #   state_color: true
          #   entities:
          #     - entity: light.grp_stue
          #       name: Stue
          #       toggle: true
          #     - entity: light.grp_spisestue
          #       name: Spisestue
          #       toggle: true

          # - type: divider
          # - entity: light.grp_kontor
          #   type: custom:multiple-entity-row
          #   name: Kontor
          #   state_header: Lys
          #   toggle: true
          #   state_color: true
          #   entities:
          #     - entity: switch.circadian_lighting_kontor
          #       name: Circadian
          #       toggle: true
          # - type: custom:slider-entity-row
          #   entity: light.grp_kontor
          #   name: Brightness
          #   hide_state: true
          #   icon: mdi:brightness-percent
          # - type: custom:slider-entity-row
          #   entity: light.grp_kontor
          #   name: Color temperature
          #   attribute: color_temp
          #   hide_state: true
          #   icon: mdi:temperature-kelvin

          # - type: divider
          # - entity: light.grp_sovevaerelse
          #   type: custom:multiple-entity-row
          #   name: Soveværelse
          #   state_header: Lys
          #   toggle: true
          #   state_color: true
          #   entities:
          #     - entity: switch.circadian_lighting_sovevaerelse
          #       name: Circadian
          #       toggle: true
          # - type: custom:slider-entity-row
          #   entity: light.grp_sovevaerelse
          #   name: Brightness
          #   hide_state: true
          #   icon: mdi:brightness-percent
          # - type: custom:slider-entity-row
          #   entity: light.grp_sovevaerelse
          #   name: Color temperature
          #   attribute: color_temp
          #   hide_state: true
          #   icon: mdi:temperature-kelvin

          # - type: divider
          # - entity: light.grp_entre
          #   type: custom:multiple-entity-row
          #   name: Entre
          #   state_header: Lys
          #   toggle: true
          #   state_color: true
          #   entities:
          #     - entity: switch.circadian_lighting_entre
          #       name: Circadian
          #       toggle: true
          # - type: custom:slider-entity-row
          #   entity: light.grp_entre
          #   name: Brightness
          #   hide_state: true
          #   icon: mdi:brightness-percent
          # - type: custom:slider-entity-row
          #   entity: light.grp_entre
          #   name: Color temperature
          #   attribute: color_temp
          #   hide_state: true
          #   icon: mdi:temperature-kelvin

          # - type: divider
          # - entity: light.grp_stue
          #   type: custom:multiple-entity-row
          #   name: Sofabord
          #   state_header: Lys
          #   toggle: true
          #   state_color: true
          #   entities:
          #     - entity: switch.circadian_lighting_stue
          #       name: Circadian
          #       toggle: true
          # - type: custom:slider-entity-row
          #   entity: light.grp_stue
          #   name: Brightness
          #   hide_state: true
          #   icon: mdi:brightness-percent
          # - type: custom:slider-entity-row
          #   entity: light.grp_stue
          #   name: Color temperature
          #   attribute: color_temp
          #   hide_state: true
          #   icon: mdi:temperature-kelvin

        title: Lights
        show_header_toggle: false

      - type: entities
        entities:
          - entity: sensor.carport_bevaegelsessensor_illuminance
            name: Illuminance
          - entity: binary_sensor.carport_bevaegelsessensor_occupancy
            name: Occupancy
          - entity: sensor.carport_bevaegelsessensor_temperature
            name: Temperature
        title: Carport bevægelsessensor

      # - type: entities
      #   entities:
      #     - input_boolean.enablewakeuplights
      #     - sensor.nextalarm
      #     - person.tom_erik
      #   title: Wake-up Lights

