title: Jyllandsgade11
views:
  - path: default_view
    title: Home
    # badges:
    #   - entity: person.tom_erik

    cards:
      - type: media-control
        entity: media_player.projector

      - type: media-control
        entity: media_player.plex_plex_cast_chromecast_3

      - type: media-control
        entity: media_player.chromecastaudio4176

      - type: media-control
        entity: media_player.plex_plex_cast_chromecast

      - type: entities
        entities:
          - entity: light.grp_hele_stue
            name: Hele Stue

          - type: divider
          - type: custom:slider-entity-row
            entity: light.grp_stue
            name: Stue
            hide_when_off: true
            toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_stue
            name: Color temp.
            hide_when_off: true
            attribute: color_temp
            hide_state: true
          - entity: switch.circadian_lighting_stue
            name: Circadian

          - type: divider
          - type: custom:slider-entity-row
            entity: light.grp_spisestue
            name: Spisestue
            hide_when_off: true
            toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_spisestue
            name: Color temp.
            hide_when_off: true
            attribute: color_temp
            hide_state: true
          - entity: switch.circadian_lighting_spisestue
            name: Circadian

          - type: divider
          - type: custom:slider-entity-row
            entity: light.grp_sovevaerelse
            name: Soveværelse
            hide_when_off: true
            toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_sovevaerelse
            name: Color temp.
            hide_when_off: true
            attribute: color_temp
            hide_state: true
          - entity: switch.circadian_lighting_sovevaerelse
            name: Circadian

          - type: divider
          - type: custom:slider-entity-row
            entity: light.grp_kokken
            name: Køkken
            hide_when_off: true
            toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_kokken
            name: Color temp.
            hide_when_off: true
            attribute: color_temp
            hide_state: true
          - entity: switch.circadian_lighting_kokken
            name: Circadian

          - type: divider
          - type: custom:slider-entity-row
            entity: light.grp_badevaerelse
            name: Badeværelse
            hide_when_off: true
            toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_badevaerelse
            name: Color temp.
            hide_when_off: true
            attribute: color_temp
            hide_state: true
          - entity: switch.circadian_lighting_badevaerelse
            name: Circadian

          - type: divider
          - type: custom:slider-entity-row
            entity: light.grp_gang
            name: Gang
            hide_when_off: true
            toggle: true
          - type: custom:slider-entity-row
            entity: light.grp_gang
            name: Color temp.
            hide_when_off: true
            attribute: color_temp
            hide_state: true
          - entity: switch.circadian_lighting_gang
            name: Circadian

        title: Lights

      - type: weather-forecast
        entity: weather.jyllandsgade11

      # - type: entities
      #   entities:
      #     - counter.stue
      #     - counter.spisestue
      #     - counter.kokken
      #     - counter.sovevaerelse
      #     - counter.badevaerelse
      #     - counter.gang

      - type: entities
        entities:
          - input_boolean.enablewakeuplights
          - sensor.nextalarm
        title: Wake-up Lights
