automation:

### STATE MACHINE
  - alias: ODLights - Lys state maskine OFF
    triggers:
      - trigger: state
        entity_id: input_select.udendors_lys_tilstand
        to: "Off"
    actions: 
      action: light.turn_off
      target:
        entity_id: light.grp_udendors_lys

  - alias: ODLights - Lys state maskine DIM
    triggers:
      - trigger: state
        entity_id: input_select.udendors_lys_tilstand
        to: "Dim"
      - trigger: state
        entity_id: input_number.udendors_dim_brightness
    actions: 
      action: light.turn_on
      target:
        entity_id: light.grp_udendors_lys
      data:
        brightness_pct: "{{ states('input_number.udendors_dim_brightness') | int }}"

  - alias: ODLights - Lys state maskine FULL
    triggers:
      - trigger: state
        entity_id: input_select.udendors_lys_tilstand
        to: "Full"
      - trigger: state
        entity_id: input_number.udendors_full_brightness
    actions: 
      action: light.turn_on
      target:
        entity_id: light.grp_udendors_lys
      data:
        brightness_pct: "{{ states('input_number.udendors_full_brightness') | int }}"

  - alias: ODLights - Dim Available
    triggers:
    - trigger: time
      at: '07:00:00'
    - trigger: time
      at: '17:00:00'
    actions:
    - action: input_boolean.turn_on
      target: 
        entity_id: input_boolean.dim_available  

  - alias: ODLights - Dim Un-Available
    triggers:
    - trigger: time
      at: '09:00:00'
    - trigger: time
      at: '00:00:00'
    actions:
    - action: input_boolean.turn_off
      target: 
        entity_id: input_boolean.dim_available  

### TRANSITIONS
  - alias: ODLights - Turn off at midnight
    triggers:
    - trigger: time
      at: 00:00:00
    actions:
      - action: input_select.select_option
        target:
          entity_id: input_select.udendors_lys_tilstand
        data:
          option: "Off"
  
  - alias: ODLights - Turn on DIM at low light
    trigger:
    - platform: numeric_state
      entity_id: sensor.carport_bevaegelsessensor_illuminance
      below: input_number.udendors_min_lux_for_dim
    conditions:
      - condition: or
        conditions:    
        - condition: time
          after: '07:00:00'
          before: 09:00:00     
        - condition: time
          after: '17:00:00'
          before: 00:00:00
    actions:
      - action: input_select.select_option
        target:
          entity_id: input_select.udendors_lys_tilstand
        data:
          option: "Dim"

  - alias: ODLights - Turn on FULL at motion detected
    trigger:
    - platform: state
      entity_id:
        - binary_sensor.carport_bevaegelsessensor_occupancy
      to: "on"
    conditions:
    - condition: state
      entity_id: input_select.udendors_lys_tilstand
      state: "Dim"
    actions:
      - action: input_select.select_option
        target:
          entity_id: input_select.udendors_lys_tilstand
        data:
          option: "Full"

  - alias: ODLights - Return after motion no longer detected 
    trigger:
    - platform: state
      entity_id:
        - binary_sensor.carport_bevaegelsessensor_occupancy
      from: "on"
      to: "off"
    conditions:
    - condition: state
      entity_id: input_select.udendors_lys_tilstand
      state: "Full"
    actions:
      - action: input_select.select_option
        target:
          entity_id: input_select.udendors_lys_tilstand
        data:
          option: "Dim"




  #   - type: motion
  #     device_id: 5541e0e7fe44afe1a922c616b3af43b0
  #     entity_id: 788c9d2ee36efd5f3c391e864410d15c
  #     domain: binary_sensor
  #     trigger: device
  #     id: Bevægelse
  #   - type: no_motion
  #     device_id: 5541e0e7fe44afe1a922c616b3af43b0
  #     entity_id: 788c9d2ee36efd5f3c391e864410d15c
  #     domain: binary_sensor
  #     trigger: device
  #     id: Ingen bevægelse
  #   - type: illuminance
  #     device_id: 5541e0e7fe44afe1a922c616b3af43b0
  #     entity_id: e673213710bda8a9d629643ed50728fc
  #     domain: sensor
  #     trigger: device
  #     above: 20
  #     id: Lyst udenfor
  #   - type: illuminance
  #     device_id: 5541e0e7fe44afe1a922c616b3af43b0
  #     entity_id: e673213710bda8a9d629643ed50728fc
  #     domain: sensor
  #     trigger: device
  #     below: 10
  #     id: Mørkt udenfor
  #   conditions:
  #   - condition: time
  #     after: '17:00:00'
  #     before: 00:00:00
  #   actions:
  #   - choose:
  #     - conditions:
  #       - condition: state
  #         entity_id: input_select.udendors_lys_tilstand
  #         state: 'Off'
  #       - condition: trigger
  #         id:
  #         - Mørkt udenfor
  #       sequence:
  #       - action: light.turn_on
  #         metadata: {}
  #         data:
  #           brightness_pct: 30
  #         target:
  #           entity_id: light.grp_udendors_lys
  #       - action: input_select.select_option
  #         metadata: {}
  #         data:
  #           option: Dim
  #         target:
  #           entity_id: input_select.udendors_lys_tilstand
  #     - conditions:
  #       - condition: state
  #         entity_id: input_select.udendors_lys_tilstand
  #         state: Dim
  #       sequence:
  #       - if:
  #         - condition: trigger
  #           id:
  #           - Bevægelse
  #         then:
  #         - action: light.turn_on
  #           metadata: {}
  #           data:
  #             brightness_pct: 100
  #           target:
  #             entity_id: light.grp_udendors_lys
  #         - action: input_select.select_option
  #           metadata: {}
  #           data:
  #             option: Full
  #       - if:
  #         - condition: trigger
  #           id:
  #           - Lyst udenfor
  #         then:
  #         - action: light.turn_off
  #           metadata: {}
  #           data: {}
  #           target:
  #             entity_id: light.grp_udendors_lys
  #         - action: input_select.select_option
  #           metadata: {}
  #           data:
  #             option: 'Off'
  #     - conditions:
  #       - condition: state
  #         entity_id: input_select.udendors_lys_tilstand
  #         state: Full
  #       - condition: trigger
  #         id:
  #         - Ingen bevægelse
  #       sequence:
  #       - action: light.turn_on
  #         metadata: {}
  #         data:
  #           brightness_pct: 30
  #         target:
  #           entity_id: light.grp_udendors_lys
  #       - action: input_select.select_option
  #         metadata: {}
  #         data:
  #           option: Dim
  #         target:
  #           entity_id: input_select.udendors_lys_tilstand
  #   mode: single
  # - id: '1743343061100'
  #   alias: Gendan lys i carport ved mangelende bevægelse
  #   description: ''
  #   triggers:
  #   - type: not_occupied
  #     device_id: 5541e0e7fe44afe1a922c616b3af43b0
  #     entity_id: 788c9d2ee36efd5f3c391e864410d15c
  #     domain: binary_sensor
  #     trigger: device
  #     for:
  #       hours: 0
  #       minutes: 3
  #       seconds: 0
  #   conditions: []
  #   actions:
  #   - action: scene.turn_on
  #     metadata: {}
  #     data: {}
  #     target:
  #       entity_id: scene.carport_nuvaerende_lys
  #   mode: single