sensor:
  - platform: time_date
    display_options:
      - "date_time_iso"
      - "date"

  - platform: template
    sensors:
      # Some documentation re. making calculations with time
      # https://community.home-assistant.io/t/calculating-with-times/35564/6
      # Conversion to timestamp_local: https://community.home-assistant.io/t/trouble-with-strptime-addition-subtraction/19412
      # Learning - Convert to float first: https://community.home-assistant.io/t/timestamp-convertion-time-difference/210514/3
      nextalarm:
        device_class: timestamp
        friendly_name: Next Alarm on Tom-Erik's P20 Pro
        value_template: >
          {% if ( states( 'sensor.tom_erik_s_p20_pro_next_alarm' ) ) %}
            {{ strptime( ( as_timestamp(states('sensor.tom_erik_s_p20_pro_next_alarm' )) | float ) | timestamp_local, "")  }}
          {% endif %}


      nextalarm_pre5:
        device_class: timestamp
        value_template: >
          {% if ( states( 'sensor.tom_erik_s_p20_pro_next_alarm' ) ) %}
            {{ strptime( ( as_timestamp(states('sensor.tom_erik_s_p20_pro_next_alarm' )) | float - 5*60 ) | timestamp_local, "")  }}
          {% endif %}

      nextalarm_pre10:
        device_class: timestamp
        value_template: >
          {% if ( states( 'sensor.tom_erik_s_p20_pro_next_alarm' ) ) %}
            {{ strptime( ( as_timestamp(states('sensor.tom_erik_s_p20_pro_next_alarm' )) | float - 10*60 ) | timestamp_local, "")  }}
          {% endif %}

      nextalarm_pre15:
        device_class: timestamp
        value_template: >
          {% if ( states( 'sensor.tom_erik_s_p20_pro_next_alarm' ) ) %}
            {{ strptime( ( as_timestamp(states('sensor.tom_erik_s_p20_pro_next_alarm' )) | float - 15*60 ) | timestamp_local, "")  }}
          {% endif %}

input_boolean:
  enablewakeuplights:
    initial: "on"
    name: "Wake up Lights"