homeassistant:
  customize:
    package.node_anchors:
      lights: &lights
        entity_id:
          - light.grp_kontor
          - light.grp_sovevaerelse

automation:
  - alias: Turn off lights when not home
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: person.tom_erik
        to:  "not_home"
        for: "00:10:00" # Must not have been home for 10 minutes
    action:
    - service: light.turn_off
      data: *lights